server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://59.110.237.72:8001/sp_test?useSSL=true
    username: root
    password: Tr@nscend_Mysql
    hikari:
      max-lifetime: 28830000
      maximum-pool-size: 9
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 #5s发送一次心跳
    lease-expiration-duration-in-seconds: 10 #10s不发送就过期
